server:
  port: 8081

# logger
logging:
  config: classpath:config/logback-spring.xml

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3307/info_base?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
        username: shenjian02
        password: sj241314jj
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:com.shenjian.chatroom.mapper/*.xml
  type-aliases-package: com.shenjian.chatroom.entity

base:
  data:
    userId-prefix: sj
    datacenterId: 1
    machineId: 1
